In [22]:
import numpy as np

In [23]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [24]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [25]:
b.ndim

2

In [26]:
a.ndim

1

In [27]:
a.shape

(3,)

In [28]:
b.shape

(2, 3)

In [29]:
a.dtype

dtype('int32')

In [30]:
a.itemsize

4

In [31]:
b.nbytes

48

In [33]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [34]:
a+=2

In [35]:
a-2

array([1, 2, 3, 4])

In [36]:
a*2

array([ 6,  8, 10, 12])

In [37]:
a/2

array([1.5, 2. , 2.5, 3. ])

In [38]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [39]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [41]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])